services:
  code-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-checker
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./prisma/data:/app/prisma/data
    restart: always

volumes:
  prisma_data:
